#!/bin/bash

PREFIX=%%PREFIX%%
BINDIR=$PREFIX/share/darwinbuild

BROOT=$1
VER=$(/usr/bin/xcodebuild -version | grep version | cut -d "-" -f 2 | cut -d ";" -f 1 | cut -d "." -f 1)
XC=$(/usr/bin/xcodebuild -version | grep Xcode | sed -e s'/^.* //g' -e 's/\.//g')

if [ "$XC" -gt "830" ];
then
	"$BINDIR/installXcode$XC" "$BROOT";
else
	if [ "$VER" -gt "920" ];
	then
		if [ "$VER" -gt "1000" ];
		then
			if [ "$VER" -gt "1600" ];
			then
				"$BINDIR/installXcode32" "$BROOT";
			else
				"$BINDIR/installXcode31" "$BROOT";	
			fi
		else
			"$BINDIR/installXcode3" "$BROOT";	
		fi
	else
		"$BINDIR/installXcode2" "$BROOT";
	fi
fi

