#!/bin/sh
#
# Copyright (c) 2017 William Kent. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 3.  Neither the name of Apple Computer, Inc. ("Apple") nor the names of
#     its contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY ITS CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#


do_ditto () {
    local path=$1
    echo ditto $path
    mkdir -p $BUILDROOT/$path
    ditto "$path" "$BUILDROOT/$path" || exit 1
}

HOST_DARWIN_VERSION=$(sw_vers -productVersion)
BUILDROOT="$1"
mkdir -p "$BUILDROOT"

do_ditto /Applications/Xcode.app/Contents/Frameworks
do_ditto /Applications/Xcode.app/Contents/SharedFrameworks
do_ditto /Applications/Xcode.app/Contents/OtherFrameworks
do_ditto /Applications/Xcode.app/Contents/PlugIns
do_ditto /Applications/Xcode.app/Contents/XPCServices

do_ditto /Applications/Xcode.app/Contents/Developer/Library
do_ditto /Applications/Xcode.app/Contents/Developer/Makefiles
do_ditto /Applications/Xcode.app/Contents/Developer/Toolchains
do_ditto /Applications/Xcode.app/Contents/Developer/Tools
do_ditto /Applications/Xcode.app/Contents/Developer/usr

do_ditto /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
ditto /Applications/Xcode.app/Contents/Info.plist $BUILDROOT/Applications/Xcode.app/Contents
ditto /Applications/Xcode.app/Contents/version.plist $BUILDROOT/Applications/Xcode.app/Contents

mkdir -p $BUILDROOT/System/Library/CoreServices
ditto /System/Library/CoreServices/SystemVersion.plist $BUILDROOT/System/Library/CoreServices

# Create extra directories required by the Xcode tools.
# While not strictly part of Xcode, without them the tools will crash.
mkdir -p $BUILDROOT/Users/$(whoami)
mkdir -p $BUILDROOT/$(getconf DARWIN_USER_DIR)
mkdir -p $BUILDOROT/$(getconf DARWIN_USER_TEMP_DIR)
mkdir -p $BUILDROOT/$(getconf DARWIN_USER_CACHE_DIR)

# Now I must remove a symbolic link, or darwinbuild will fail later.
if [ "$HOST_DARWIN_VERSION" == "10.13" ]; then
    rm $BUILDROOT/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
    mv $BUILDROOT/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk $BUILDROOT/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk

    mkdir -p $BUILDROOT/var/db
    ln -s /Applications/Xcode.app/Contents/Developer $BUILDROOT/var/db/xcode_select_link
elif [ "$HOST_DARWIN_VERSION" == "10.12" ]; then
    rm $BUILDROOT/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
    mv $BUILDROOT/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk $BUILDROOT/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
fi
