#!/bin/bash

BINDIR=/usr/local/share/darwinbuild

BROOT=$1
VER=$(/usr/bin/xcodebuild -version | grep version | cut -d "-" -f 2 | cut -d ";" -f 1 | cut -d "." -f 1)

if [ "$VER" -gt "920" ];
then
	"$BINDIR/installXcode3" "$BROOT";	
else
	"$BINDIR/installXcode2" "$BROOT";
fi
