#!/bin/sh

do_ditto () {
    local path=$1
    echo ditto $path
    mkdir -p $BUILDROOT/$path
    ditto "$path" "$BUILDROOT/$path" || exit 1
}

BUILDROOT="$1"
mkdir -p "$BUILDROOT"

do_ditto /Applications/Xcode.app/Contents/Frameworks
do_ditto /Applications/Xcode.app/Contents/SharedFrameworks
do_ditto /Applications/Xcode.app/Contents/OtherFrameworks
do_ditto /Applications/Xcode.app/Contents/Plugins
do_ditto /Applications/Xcode.app/Contents/XPCServices

do_ditto /Applications/Xcode.app/Contents/Developer/Library
do_ditto /Applications/Xcode.app/Contents/Developer/Makefiles
do_ditto /Applications/Xcode.app/Contents/Developer/Toolchains
do_ditto /Applications/Xcode.app/Contents/Developer/Tools
do_ditto /Applications/Xcode.app/Contents/Developer/usr

do_ditto /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
