#!/usr/bin/env python
import os
for i in range(81,102):
	print " ... trying to close(%s)" % i
	try:
		os.close(i)
		print " ... closed %s" % i
		exit(1)
	except Exception, e:
		# test for EBADF
		if e.errno == 9:
			print " ... got EBADF as expected"
		else:
			print " ... got wrong error back: %s" % e
			exit(2)
exit(0)
