.ig
Copyright (c) 2010 Apple Inc.  All rights reserved.
@APPLE_BSD_LICENSE_HEADER_START@
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1.  Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
2.  Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
3.  Neither the name of Apple Computer, Inc. ("Apple") nor the names of
    its contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
@APPLE_BSD_LICENSE_HEADER_END@
..
.Dd 6 Apr, 2010
.Dt darwinup 1
.Os Darwin
.Sh NAME
.Nm darwinup
.Nd Install, uninstall, and manage roots
.Sh SYNOPSIS
.Nm
.Op Fl dfnv
.Op Fl p Ar path
.Ar subcommand 
.Op Ar arguments ...
.Sh DESCRIPTION
.Nm 
allows you to manage roots, or
archives, of files that replace parts of your system. This is useful
for installing a new version of a library or tool on your system while 
allowing you to uninstall the files and revert back to the originals 
safely and easily.
.Sh SUBCOMMANDS
.Bl -tag -width -indent
.It Ar files Ar archives
List the files and directories in the 
.Ar archive .
.It Ar install Ar path
Install the root at 
.Ar path .
.It Ar list Op Ar archive
List archives that are installed. You may optionally provide an
archive specification to limit which archives get listed. 
.It Ar uninstall Ar archives
Uninstall the specified archive.
.It Ar upgrade Ar path
Find the last archive that was installed with the same name (basename of 
path), and replace it with the root at 
.Ar path .
.It Ar verify Ar archive
List all of the information about 
.Ar archive .
This includes status letters
detailing how the archive differs from whats on disk
.El
.Sh STATUS SYMBOLS
.Bl -tag -width -indent
.It ? 
Unknown state. Probably a bug.
.It !
Missing file during uninstall. Darwinup expected a file or directory to 
exist, but it did not. This could be a bug in darwinup, but most likely 
another tool or software update removed a file that darwinup had been 
tracking. It can also be caused by an installation failing due to an
object changing type (see FORCING OPERATIONS below), and the subsequent 
rollback finding the root only partially installed. Since these all 
happen during uninstall, they are typically safe to ignore, since darwinup 
was going to delete the object anyway.
.It A
Added. No previous file or directory existed so the file or directory was
added to your system.
.It E
External change. The file you are installing is different than the 
last file you installed, but it is identical to what was actually found
on disk. This probably means something manually installed a root or software
update without darwinup knowing about it. This is usually harmless. 
.It M 
Mode change. Only changes to permission or ownership were needed to
uninstall the file or directory. 
.It R
Removed. No previous file or directory existed, so the uninstall process
removed the file. 
.It U
Updated. During installation, the file or directory replaces an existing 
object at the same path. During uninstallation, the previous version of
the file was restored. 
.Sh SUPPORTED PATHS
.Sh ARCHIVE SPECIFICATIONS
.Sh FORCING OPERATIONS
