.ig
Copyright (c) 2010 Apple Inc.  All rights reserved.
@APPLE_BSD_LICENSE_HEADER_START@
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1.  Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
2.  Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
3.  Neither the name of Apple Computer, Inc. ("Apple") nor the names of
    its contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
@APPLE_BSD_LICENSE_HEADER_END@
..
.Dd 6 Apr, 2010
.Dt darwinup 1
.Os Darwin
.Sh NAME
.Nm darwinup
.Nd Install, uninstall, and manage roots
.Sh SYNOPSIS
.Nm
.Op Fl dfnv
.Op Fl p Ar path
.Ar subcommand 
.Op Ar arguments ...
.Sh DESCRIPTION
.Nm 
allows you to manage roots, or
archives, of files that replace parts of your system. This is useful
for installing a new version of a library or tool on your system while allowing you to
uninstall the files and revert back to the originals safely and easily.
.Sh SUBCOMMANDS
.Bl -tag -width -indent
.It Ar files Ar archives
.It Ar install Ar path
.It Ar list Op Ar archive
.It Ar uninstall Ar archives
.It Ar upgrade Ar path
.It Ar verify Ar archive
.El
.Sh SUPPORTED PATHS
.Sh ARCHIVE SPECIFICATIONS
.Sh FORCING OPERATIONS
